apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportbot-deployment
  labels:
    app: reportbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportbot
  template:
    metadata:
      labels:
        app: reportbot
    spec:
      volumes:
        - name: config
          configMap:
            name: reportbotconfig
      containers:
        - name: reportbot
          image: mikej091/reportbot:0.1.3
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: token
              valueFrom:
                secretKeyRef:
                  name: reportbotsecrets
                  key: token
            - name: activation
              value: $report
            - name: config
              value: /config/config.yaml
