apiVersion: v1
kind: Service
metadata:
  name: reportbot-service
spec:
  type: NodePort
  selector:
    app: reportbot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007